### ISSUE TITLE
'visual mode' to 'command mode' will appear garbled

### ISSUE THREAD

**Issue by linjialiang** [k-takata/vim-win32-installer#4] opened 2017-11-01 01:20 UTC
This happens if the `visual mode` is switched directly to the `command mode`

![default](https://user-images.githubusercontent.com/8848263/32255766-b9450c4e-bee5-11e7-8175-7a152da09712.png)

**Comment by k-takata** [comment] 2017-11-01 01:53
This is not the right place to report an issue of Vim, because this repository is a workbench for [vim/vim-win32-installer](https://github.com/vim/vim-win32-installer) (as I wrote in the description of this repository).

Normally you can report to the [official repository](https://github.com/vim/vim). If the problem is specific to the Win32 nightly builds, report to [vim/vim-win32-installer](https://github.com/vim/vim-win32-installer).

Please do not forget to write the Vim version (including the patchlevel) and reproducing steps when you report the issue.
Also make sure that it is not the problem of a plugin. (Use `vim --clean` to execute Vim without plugins.)

Closing.

**Closed as completed by k-takata** 2017-11-01 01:53 UTC

**Comment by chrisbra** [comment] 2017-11-01 07:04
BTW: If you are talking about the `:'<,'>` stuff, then this is a feature you can read about at `:h v_:`
